/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as MataMataRouteImport } from './routes/mata-mata'
import { Route as GruposRouteImport } from './routes/grupos'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as IndexRouteImport } from './routes/index'

const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const MataMataRoute = MataMataRouteImport.update({
  id: '/mata-mata',
  path: '/mata-mata',
  getParentRoute: () => rootRouteImport,
} as any)
const GruposRoute = GruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/grupos': typeof GruposRoute
  '/mata-mata': typeof MataMataRoute
  '/ranking': typeof RankingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/grupos': typeof GruposRoute
  '/mata-mata': typeof MataMataRoute
  '/ranking': typeof RankingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/grupos': typeof GruposRoute
  '/mata-mata': typeof MataMataRoute
  '/ranking': typeof RankingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calendario' | '/grupos' | '/mata-mata' | '/ranking'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calendario' | '/grupos' | '/mata-mata' | '/ranking'
  id: '__root__' | '/' | '/calendario' | '/grupos' | '/mata-mata' | '/ranking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarioRoute: typeof CalendarioRoute
  GruposRoute: typeof GruposRoute
  MataMataRoute: typeof MataMataRoute
  RankingRoute: typeof RankingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mata-mata': {
      id: '/mata-mata'
      path: '/mata-mata'
      fullPath: '/mata-mata'
      preLoaderRoute: typeof MataMataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupos': {
      id: '/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof GruposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarioRoute: CalendarioRoute,
  GruposRoute: GruposRoute,
  MataMataRoute: MataMataRoute,
  RankingRoute: RankingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
